version: '3.8'

services:
  # 1. Base de Datos (SQL Server)
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gestion_gastos_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSeguro123!
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data

  # 2. Backend (.NET)
  api:
    build:
      context: ./GestionDatos.API 
    container_name: gestion_gastos_api
    ports:
      - "5000:8080"
    environment:
      # Conectamos la API automáticamente a la base de datos de arriba
      - ConnectionStrings__DefaultConnection=Server=db;Database=GestionGastosDb;User Id=sa;Password=TuPasswordSeguro123!;Encrypt=False;
    depends_on:
      - db

  # 3. Frontend (React)
  frontend:
    build:
      context: ./mi-proyecto-react 
    container_name: gestion_gastos_front
    ports:
      - "3000:80"
    depends_on:
      - api